context:
  name: diffstarpop
  version: "0.0.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/diffstarpop-${{ version }}.tar.gz
  sha256: 7cafeacf7cda3202c616c9bc625e678ac94ad784f25863d289abea2c8ebedfa2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=7
    - pip
  run:
    - python >=${{ python_min }}
    - diffmah >=0.7.0
    - diffstar >=0.3.3
    - numpy
    - jax
    - dsps

tests:
  - python:
      imports:
        - diffstarpop
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/ArgonneCPAC/diffstarpop
  summary: Library for differentiable generation of star formation histories
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - beckermr
